### ISSUE TITLE
Implement improved styling

### ISSUE THREAD

**Issue by therealmoss** [ChristChurchMayfair/ccm_blog#2]
**[See styling bundle branch](https://github.com/ChristChurchMayfair/ccm_blog/tree/styling-bundle)**

**Changelog**
- Adds branding (fonts, colours)
- Changes to a two column layout on desktop
- Improved mobile styling
- A bunch of other small things
- Trimmed out some unnecessary code, including simplifying the grid styling

**Bad things**
- I've broken it a bit, so now the sidebar stays when you click on posts on mobile (this isn't an issue on desktop, should be an easy fix)
- Font sizes are a bit all over the place

**Comment by tomduckering** [comment]
I think this is sorted.
